
try{let a =undefined
console.log(a[0]);}
catch (error){
    console.log("error handled",error);
    
}
finally{
    console.log("finally");
    

}
